language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn build
  - yarn test

notifications:
  slack:
    secure: Rl+OimIGgt3/t3Msc2m3AIR79J1gTejJUOtbycrOdil98bAFWogGCtdNCD139ML9VpvxoggLarkvFDattsdL767HZDIoUvgq+WieJj4WdWbr20mHN0JpM4uJ5nMoTWGJbuUrzfP1z660oCF/6c5mmWXXH7sZ1YL7ev/sxOJ4sayvEbIkE3HJvjOHFMVwtBbDlXYb/xl93Syv7IRCCnP3ojdHya/Bz2LNzQupGmJnDyXGaErCey96V/pCP/g7ipRe4seFICYTs/puQF198CMJ+GjndrOdRb/SVL3W5McnDf+HnFj8LsHLYTVOOLaTKkYxFD8478ovf/QTGTqbnCK3yUIDo4TKpC/o1lR2GIfRQBjG9+3rrr7/iMMJ+qLOaVIi9E3L8terq3zYHliU7vqo42QOt2ciG6w+bNS75MQK2NrMm+zF4zLT4LBuOXQ1tV83UafenYlzKlnAcQcVca/qp0rIhkvs5w9ErYqV40ImqBFcjJqKPz1DloOOWd8zczw5nQR0g15GwNBgNBgkWMnUzrUCTvf/BHrAI+prbg4R/z58HnDJozagFnCATFGQbBpVeKrjPNAB5ZBWtaLOptTfaSJxikHiw4XAGIBAc4rdxnmRRraGH8+ITbUaoVfqWhB0vCj7b2XqCmzJCxwz5hI96bZ5FRfsqoOq/NV3iugxSPQ=

env:
  global:
    - secure: Ol3ZGvwpWiSP9ZXO9kC7SRxkJ6asJYx8asalXhjZboMTEsHOU5nFLVZOJFGiCFkNQEsf0gsIOr1PVrf0LD2kepBjq6svjbuCYGkMlegL3iW2z2LgQaDSo1bmOCosTw7EU6k5L4veBkAbWk9zLqCl24Ri8EhRmM9sOurxcWu6hjCUARsiYtUaW6QSeYcFrTeYZCE4Rw/bCSgoDnjOCe8dmpiNC1MNGKQDCaL4xwtdXbpJvn5yVZqlu/zjQUP1m0qgNX6ILH9ewBGQKET/XWYFTpgVndVqDg3y5+1tLB4aaT8hxS/MvDUM58KjV2OilQhZo+RLqffyP374MfHp7R2vZfptw/8LoTLfxTdC4hJ9oqNwQDkLxpx5ax/kgf8Xo+uX4rqM477O67OyvkXf3/neg8tlqt71UtVrlFc+sTe9gqZ6kJaNhfxCuhODDh9EJb0l9YKQwuPTO/H+E0CqZshgpZnE9FxOaMCpDPG+CVYTlGo5U6lrBjGBDOiZZiZOYh8znJLPtahL7rnOzvvCl7Lbam0mxcWnFGX7upWdk3VDm6IpdZGtsFBYXLegWCJkrJT6JDVkyBecdDJ9mWA545kS94PY+VM3ce0NB3xAV7QmrM3NXE5c7NB/qhD/yRisfjeAOGdcBybd0mJqZriiB/iSIYV9Rjvz4bn1ItX+GBew3EU=
    - secure: YvkK2mcrcWbN7OBKbEpA30ZFIK3eiF2dFPOqZVyxg2xs+UEv7NK7lidAAinbLgzCuc51588twoDUigi6XKXkNtudEzrMokHOD3ntxKkR9SmgKIY8LGZjDfHUEuC69XqcCFFY1f1QfG1TYCDhcheyw4el4KAv474dD/NkZPpHDHQaQfJc63r9jCiCiszf5zbnZjznoYsBVxHpAFie6GxW51sCQu8qOjauTG4Ca9LJNq6eVYRQyAcHhbm32Fd8jzItllwzy9eMNyWHe7cTyeSOvt86mn+cEYkmNi70EGCuGayIGDhn2ED6C8maVkq8VIob4Ctm470c7C0msaLoJf5EhWFQU/MEqSsrVJBFWpSVyL9H6lQ5SSt9pT1xTu3s74s9qNVULGAKKGw8qBULY+QUTj4mJM38krRfaZQmPX4+8bzAlNTZFRwZ0X9jmar9BaPpUukyto725fusZjonvaMGoJ59YJvpBNyLO2gSRLkUNtJ3JBV3PPmQALDxWDQpy8xjQ8o0anQpnjFq5v7rCKikeUXRd2YOQ1E26XYN3QuvCgIkrmR4Yl9nmsGl5/3Uq+BMmEO3gwrJgHVsKyUhN3DG2BZo1Hrt/CVbtmzz+c0aCVfghherYIXs2ECtji6SfhABsAJsbRqwg6hZL87sJObV+mpM8YxlvF6slDQ0MR673+A=
    - secure: gjLqYvzSe4cg0Dns//rvlRFH7CU6qC7NV0dW8cHRO43Bv4gzBNbqk7CfivsdJI4x5ubzOYCvkco2Gy+MLL9mFpXwI1Pdw9SQtP/OpYakhcFABhrb7cD57c0A3Zs6ekRluaO3xSThcLmlwTf5KmfQ1sneHFruWOiu9BiNDknnf6bGzB6qAE1G1B3ElVDzPGd5IzjW+mtAIwVL9yYyk8kQmcJPrJd0PPRz+AFXZbNxMNeuwNnB/UUXesZLVXOVVL0qDrDKsMnrV2VOcjG/+6mfTcwoC7nMw1eFZNRS5pEKwrFfslLuuezMCwVOLk4e+8MDQ0gE8JmKLEWSiB/EcpjUGqEi3Q32ycEp2Sz988y/MOgvhHp79zXBc9KwlOSyNlgvI5AOa3JuGlFKyTiv/7DLe6lweVwpY43V7FOzHLxmQ4B7hZFS+Qkd0TRQScAeeNTLj2/avaQfUE1mgABGqQ6tpis2j9tHuZyvHOVrGImvN001RZXhFQlp4qnCESGUvUzKcbpukhp/kTX7tO7Ydi61Rf+KcU8uJVobmQ1coXiNmiivLPZm2UNmx6rnxkqGGE0fYwu5cKPTfwzNFaafdueeHxXsMINPinE2ggwySrnClDP172k2Y2f32G/e6VlXZDvWCNDUALZre0j9HXHXZh4pzZAscOPqkbyEksDbqPRPboo=
    - export GIT_AUTHOR_NAME="EndemolShineGroupUser"
    - export GIT_AUTHOR_EMAIL="tech@endemolshine.com"
    - export GIT_COMMITTER_NAME="EndemolShineGroupUser"
    - export GIT_COMMITTER_EMAIL="tech@endemolshine.com"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      after_success:
        - yarn global add codecov
        - codecov
    - stage: release
      if: branch = master AND type != pull_request
      after_success:
        - yarn semantic-release
        - git clone https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
        - cd $TRAVIS_REPO_SLUG
        - git fetch --all
        - git merge origin/master
        - git push
